[package]
name = "yasseinshehata/myrobloxgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileService = "alreadypro/profileservice@1.0.4"